name: pretty_imports
version: 0.0.1
author: 'Pete Blois <peteblois@github.com>'
description: Superfluous imports, away!
dependencies:
  analyzer: '>=0.15.6 <0.16.0'
  barback: '>=0.11.1 <0.14.0'
  path: '>=0.9.0 <2.0.0'
  source_maps: '>=0.9.2 <0.10.0'
dev_dependencies:
  unittest: '>=0.10.1 <0.11.0'
  code_transformers: '>=0.1.4 <0.2.0'
environment:
  sdk: '>=1.0.0 <2.0.0'

transformers:
- pretty_imports
- $dart2js:
    $include: []